language: node_js

node_js:
   - "8.10.0"

before_script: # commands to run before the build step
   - npm install -g --silent @angular/cli

cache:
  directories:
    - "node_modules"

script: # the build step
   - ng test --single-run true --reporters progress
   - ng build --prod